# Minimal makefile for Sphinx documentation 
# 

# You can set these variables from the command line. 
SPHINXOPTS = 
SPHINXBUILD = sphinx-build 
SPHINXPROJ = ESP8266ArduinoCore 
SOURCEDIR = . 
BUILDDIR = _build 

# Put it first so that "make" without argument is like "make help". 
help:
	@$(SPHINXBUILD) -M help "$(SOURCEDIR)" "$(BUILDDIR)" $(SPHINXOPTS) $(O)
